apiVersion: v1
kind: Service
metadata:
  name: frontend-app-service
  namespace: antcolony
spec:
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
